spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sys?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false

logging:
  level:
    root: INFO
    com.xiaoa: DEBUG
    org.springframework.web: INFO
